### ISSUE TITLE
Create an extension to export all project data

### ISSUE THREAD

**Issue by louislang** [phylum-dev/community-extensions#36]
We need an extension for exporting data across all projects. This extension should iterate through a users projects and return either a CSV or JSON response for each.

**Comment by cd-work** [comment]
Could you be more precise about "all project data"? Do we want latest analysis results, packages, project names?

**Comment by louislang** [comment]
The goal is to automate the process of going through each project, in the event a user has hundreds or thousands of projects. The resulting data should be in a format to easily be put into another system, so JSON or CSV. I expect iterating through each project and gathering the JSON should be sufficient and should include: project name and issues.

**Comment by cd-work** [comment]
> should include: project name and issues.

So we do **not** want to know dependencies and lockfiles? Just the analysis **results**.

So I'd imagine something like this:

```json
[{
    "project": "cli",
    "issues": [{
        // CVE-ID, description, title, score, etc.
    }, ...]
}, ...]
```
