### ISSUE TITLE
Update `snyk-import` to account for organizations

### ISSUE THREAD

**Issue by maxrake** [phylum-dev/community-extensions#46]
Organization support was first added to the extension API in CLI v7.0.0 ([See commit `f890fea`](https://github.com/phylum-dev/cli/commit/f890fea) or PR phylum-dev/cli#1490) and exposed for consumers in CLI (v7.1.4?) (see PR phylum-dev/cli#1532).

A review of the default and community extensions revealed only one use of one of these changed API calls:

* `snyk-import`, for `createProject`
  * https://github.com/phylum-dev/community-extensions/blob/4c878e27930a9cdd332d65b066e514b778ef9a9a/snyk-import/main.ts#L69

This issue is meant to track the progress in updating to the use of organizations. The `snyk-import` extension can be updated at that time or perhaps pre-emptively.

**Comment by cd-work** [comment]
Do we even need this extension now that it's built into the UI? I don't think anyone should be using this...

**Comment by maxrake** [comment]
Good point. This extension can likely be removed now...pending a confirmation from @furi0us333 that there is no need for it anymore.

**Comment by kylewillmon** [comment]
I've confirmed with @furi0us333 that this can be deleted.
